// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALCaN-RYu_T5ix_ReGbXWDWJn-WWKVvfw',
    appId: '1:626705000356:web:e37edcc2d1503daff74331',
    messagingSenderId: '626705000356',
    projectId: 'fir-eb6ce',
    authDomain: 'fir-eb6ce.firebaseapp.com',
    storageBucket: 'fir-eb6ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKM3OFoKXvs_D8XAgVyxpQXtPffNPmtTY',
    appId: '1:626705000356:android:b75f15c9e89df8b6f74331',
    messagingSenderId: '626705000356',
    projectId: 'fir-eb6ce',
    storageBucket: 'fir-eb6ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOfNeqmvA4fKyw_-Zo0Fo7WIcdNPXqi8E',
    appId: '1:626705000356:ios:7349bab073b2af48f74331',
    messagingSenderId: '626705000356',
    projectId: 'fir-eb6ce',
    storageBucket: 'fir-eb6ce.appspot.com',
    iosBundleId: 'com.example.untitledsaggo123',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOfNeqmvA4fKyw_-Zo0Fo7WIcdNPXqi8E',
    appId: '1:626705000356:ios:c42626599b2890d6f74331',
    messagingSenderId: '626705000356',
    projectId: 'fir-eb6ce',
    storageBucket: 'fir-eb6ce.appspot.com',
    iosBundleId: 'com.example.untitledsaggo123.RunnerTests',
  );
}
